### ISSUE TITLE
Swift 4 release not available via cocoapods

### ISSUE THREAD

**Issue by dhiraj-das** [paulz/ImageCoordinateSpace#3]
Please merge the swift 4 branch for use via cocoapods.

**Comment by paulz** [comment]
What version of cocoa-pods are you using?
Swift 4 version Requires cocoapods version 1.3.1 and above, see Podspec: https://github.com/CocoaPods/Specs/blob/master/Specs/4/2/4/ImageCoordinateSpace/1.0.5/ImageCoordinateSpace.podspec.json

**Comment by paulz** [comment]
Just verified the version 1.0.5 is available via cocoapods, see spec above and it supports Swift 4.
If you need older versions of Swift, check out version 1.0.3 that works with Swift 3.2
